
#General settings
[general]
	#Use config instead of datapack
	use_config = true

	#List settings
	#Syntax: ["modid:block|weight"]
	#Example: ["minecraft:stone|2","minecraft:dirt|1"]
	#Forge tags are supported
	[general.lists]
		#Cobble gen
		block_list_cobble = ["minecraft:cobblestone|100", "minecraft:deepslate|1"]
		#Stone gen
		block_list_stone = ["minecraft:stone|100"]
		#Basalt gen
		block_list_basalt = ["minecraft:basalt|100"]

		#Custom settings
		[general.lists.custom]
			#Custom generators
			#Syntax: [gen]
			#Gen: [type, block, list]
			#Type: cobblestone, stone
			#Block: resource location of the block below the generated block
			#List: see List settings
			#Examples:
			#custom_generators = [
			#   ["cobblestone", "minecraft:diamond_block", ["minecraft:diamond_block"]],
			#   ["cobblestone", "minecraft:dirt", ["forge:dirt"]],
			#   ["cobblestone", "minecraft:white_wool", ["minecraft:wool"]]]
			custom_generators = [["stone", "minecraft:bedrock", ["minecraft:diorite|10", "minecraft:andesite|15", "minecraft:granite|10", "create:limestone|8", "create:veridium|8", "create:scoria|8"]], ["cobblestone", "minecraft:deepslate", ["minecraft:cobblestone|100", "minecraft:iron_ore|4", "minecraft:gold_ore|2", "minecraft:copper_ore|4"]], ["cobblestone", "create:andesite_casing", ["minecraft:cobblestone|100", "minecraft:andesite|25"]], ["cobblestone", "create:copper_casing", ["minecraft:cobblestone|100", "minecraft:copper_ore|10"]], ["cobblestone", "create:brass_casing", ["minecraft:cobblestone|100", "create:zinc_ore|40", "minecraft:copper_ore|40", "minecraft:andesite|40"]]]

