#Range: 1 ~ 4
itemsPerColumn = 4
#Range: 1 ~ 4
itemsPerRow = 4
diyData = true
showDevData = false
enchantsBlacklist = ["worldgen", "dungeon"]
hiddenTabs = ["worldgen"]
dimensionsBlacklist = [-11]
disableLootManagerReloading = false

